steps:
- download: current
  displayName: ðŸ”» Download deployables
  artifact: deployables-Linux

- powershell: dotnet nuget push "$(Resolve-Path '$(Pipeline.Workspace)\deployables-Linux\')*.nupkg" -s $(ci_feed) -k azdo --skip-duplicate
  displayName: ðŸ“¦ Push packages to CI feed
  condition: and(succeeded(), ne(variables['ci_feed'], ''), ne(variables['Build.Reason'], 'PullRequest'))
